### ISSUE TITLE
 CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE does not work

### ISSUE THREAD

**Issue by Badjau** [mctechnology17/zmk-nice-oled#1]
The display does not change to blank after the timer. Sleep works fine though (CONFIG_ZMK_IDLE_SLEEP_TIMEOUT).
Tested different durations.

**Comment by mctechnology17** [comment]
Hello, thank you very much for the report! I just uploaded the changes, could you tell me if you still have the problem?

**Comment by Badjau** [comment]
Working now, cheers!
